name: test
on: [push, pull_request]
jobs:
  golang:
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.20"'
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-$GITHUB_REPOSITORY-${{ hashFiles('**/go.mod') }}
      - name: go vet
        run: go vet ./...
      - name: go test race
        run: go test -v -race -parallel 4 -coverprofile=covprofile -covermode=atomic ./...
      - name: install goveralls
        env:
          GO111MODULE: off
        run: go install github.com/mattn/goveralls@v0.0.12
      - name: send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
